#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

# echo "Crystal Version" && crystal -v
# echo "Node Version" && node -v
# echo "NPM Version" && npm -v

shards check || shards install
crystal tool format --check
yarn install --frozen-lockfile --no-progress

echo "Running 'npx browserslist@latest --update-db'"
npx browserslist@latest --update-db

yarn prod

crystal build tasks.cr -o ./lucky_tasks

script/setup

echo "Crystal Version" && crystal -v
echo "Node Version" && node -v
echo "NPM Version" && npm -v

# tbd
# ./lucky_tasks db.create
# ./lucky_tasks db.migrate
# ./lucky_tasks db.seed.required_data

# lucky dev &

# echo "Ready"

# sleep indefinitely

# crystal spec
